### PR TITLE
Fix weird plugin loading behavior

### PR DESCRIPTION
**Pull request by noodlebox**
Calling `unload()` here doesn't make sense, and neither would `load()`, since that gets called later anyway. It's also inconsistent with the [behavior of the Windows version](https://github.com/Jiiks/BetterDiscordApp/blob/bdf889e14f387a18d2054e1883c4cc4129e6af27/lib/BetterDiscord.js#L425). I'm assuming this is a typo.

I don't have a Mac to test it on, though this should be a harmless fix for some weird platform-specific bugs in plugins implementing `unload`.

### CODE REVIEW

**Comment by iVEnoVaLue** [comment]
Not really. In this loader there is hot loading implemented. whenever you change something  in the base script it reloads automatically, which makes plugins load DOM elements several times. This was just allowing to make use of the unload function of the plugin to clean anything related to the plugin from DOM.

**Comment by iVEnoVaLue** [comment]
The only typo is that's called twice. Anyway, i haven't changed stuff in this repo for a long time. 
This is the last thing i was working on https://bitbucket.org/ivenovalue/betterdiscord/src/abe53d13d0f37d8991b327add120d20f45edf702/lib/?at=master

**Comment by noodlebox** [comment]
Oh, I didn't realize that. The issue that I had run into before was in a plugin that assumed jQuery would be available in the global scope by the time `load()` or `unload()` ever got called, and in this one case, it's not.

**Comment by iVEnoVaLue** [comment]
Well jQuery should be there before any plugin loading anyway. That's why I started working on a local version.

**Pull request closed without merging**
